const dashboardUrl = process.env.NEXT_PUBLIC_DASHBOARD_URL ?? "http://localhost:3001";

const stages = [
  { number: "01", label: "Listen", title: "Start with the farmer.", copy: "A crop question arrives in a channel they already know. Their story stays attached as the conversation moves." },
  { number: "02", label: "Connect", title: "Bring good options closer.", copy: "Specialist workflows connect the need to local input supply and a payment path that fits the moment." },
  { number: "03", label: "Follow through", title: "Make the next step clear.", copy: "The partner team sees where support is needed and can follow the journey beyond the first answer." },
];

const capabilities = [
  { symbol: "↗", title: "One continuous journey", copy: "SMS, WhatsApp, rich messaging and email are designed to share context across a single farmer session." },
  { symbol: "⌖", title: "Local supply, in context", copy: "Connect crop guidance to dealer availability, distance and a practical next step." },
  { symbol: "◷", title: "Partner visibility", copy: "Give cooperatives and NGOs an operations view of conversations, reservations and support activity." },
];

export default function Home() {
  return (
    <main className="site-shell">
      <header className="site-header">
        <a className="wordmark" href="#home" aria-label="HarvestOS home"><BrandMark/><span>harvest<span className="wordmark-os">os</span></span></a>
        <nav className="desktop-nav" aria-label="Main navigation"><a href="#platform">Platform</a><a href="#journey">How it works</a><a href="#system">System design</a></nav>
        <div className="header-actions"><a className="header-login" href={`${dashboardUrl}/login`}>Partner sign in</a><a className="button button-dark button-small" href="#platform">Explore HarvestOS <span>↗</span></a></div>
        <details className="mobile-menu"><summary aria-label="Open navigation"><span></span><span></span></summary><nav aria-label="Mobile navigation"><a href="#platform">Platform</a><a href="#journey">How it works</a><a href="#system">System design</a><a href={`${dashboardUrl}/login`}>Partner sign in ↗</a></nav></details>
      </header>

      <section className="hero" id="home">
        <div className="hero-grain" aria-hidden="true"/>
        <div className="hero-copy"><div className="eyebrow"><span className="eyebrow-orbit"><i/></span> CONNECTED FARMER COMMERCE <span className="eyebrow-divider"/> BUILT FOR AFRICA</div><h1>From first question<br/>to <em>next harvest.</em></h1><p className="hero-lede">The operating layer that connects a farmer’s crop question to local supply, flexible finance, and the people supporting their season.</p><div className="hero-actions"><a className="button button-dark" href="#platform">Discover the platform <span>↗</span></a><a className="button button-outline" href={`${dashboardUrl}/login`}><span className="button-play">↗</span> Partner workspace</a></div><div className="hero-proof"><span className="proof-avatars"><i>F</i><i>O</i><i>+</i></span><span>Designed for the people behind every harvest.</span></div></div>
        <ProductPreview/>
        <div className="hero-index"><span>01</span><i/> A FARMER-FIRST COMMERCE PLATFORM</div>
      </section>

      <section className="trust-strip" aria-label="Designed for agricultural partners"><span>BUILT AROUND THE WAY FARMERS ALREADY CONNECT</span><div><b>SMS</b><i/> <b>WHATSAPP</b><i/> <b>RICH MESSAGING</b><i/> <b>EMAIL</b></div><span className="strip-note">One thread. More ways forward.</span></section>

      <section className="platform-section section-pad" id="platform"><div className="section-intro"><div><p className="section-eyebrow">THE PLATFORM <span>—</span> 01</p><h2>Good support should<br/>go <em>all the way.</em></h2></div><p className="section-intro-copy">Farmers are often left to bridge advice, local dealers, and financing on their own. HarvestOS brings those parts into one partner-ready service journey.</p></div><div className="capability-grid">{capabilities.map((item,index)=><article className="capability-card" key={item.title}><div className={`cap-icon cap-icon-${index}`}>{item.symbol}</div><span className="card-index">0{index+1} / 03</span><h3>{item.title}</h3><p>{item.copy}</p><a href="#journey" aria-label={`Explore ${item.title}`}>↗</a></article>)}</div></section>

      <section className="journey-section" id="journey"><div className="journey-inner section-pad"><div className="journey-head"><div><p className="section-eyebrow">ONE SESSION, MORE POSSIBILITIES <span>—</span> 02</p><h2>Built to move<br/>with the <em>moment.</em></h2></div><p>Each step uses the channel and partner best suited to what happens next, with session context carried through the experience.</p></div><div className="stage-list">{stages.map((stage,index)=><article className="stage-row" key={stage.number}><div className="stage-number">{stage.number}<span/></div><div className="stage-label">{stage.label}</div><div className="stage-copy"><h3>{stage.title}</h3><p>{stage.copy}</p></div><div className={`stage-symbol stage-symbol-${index}`} aria-hidden="true">{index===0?<><span>SMS</span><i>↗</i><span>WA</span></>:index===1?<><span>⌖</span><i>+</i><span>₦</span></>:<><span>↗</span><i>→</i><span>✓</span></>}</div></article>)}</div></div></section>

      <section className="system-section section-pad" id="system"><div className="system-heading"><div><p className="section-eyebrow">SYSTEM DESIGN <span>—</span> 03</p><h2>A clear path from<br/><em>message to action.</em></h2></div><p>Channel adapters keep delivery separate from the journey logic. Shared session state gives specialist workflows the context to coordinate a useful next step.</p></div><div className="system-map"><div className="system-node node-farmer"><span className="node-icon">⌁</span><div><small>ENTRY POINT</small><b>Farmer channels</b><span>SMS · WhatsApp · RCS · Email</span></div></div><div className="map-connector"><i/></div><div className="system-node node-api"><span className="node-icon">⌘</span><div><small>INGRESS & DELIVERY</small><b>Channel adapters</b><span>Normalize · validate · dispatch</span></div></div><div className="map-connector"><i/></div><div className="system-node node-orchestrator"><span className="node-icon">✳</span><div><small>JOURNEY CONTROL</small><b>Orchestrator</b><span>Intent · continuity · handoff</span></div></div><div className="specialist-branch"><span>SHARED SESSION CONTEXT</span><i/><div><b>Diagnosis</b><b>Commerce</b><b>Finance</b><b>Logistics</b></div></div><div className="map-connector"><i/></div><div className="system-node node-data"><span className="node-icon">◫</span><div><small>PARTNER OPERATIONS</small><b>Session store + dashboard</b><span>Memory locally · DynamoDB in AWS mode</span></div></div></div><div className="system-note"><span>↗</span><p>Architecture is designed for independent channel adapters, replaceable agent backends, and a shared source of journey state.</p><a href={`${dashboardUrl}/login`}>Open partner workspace <b>→</b></a></div></section>

      <section className="closing-section"><div className="closing-orbit orbit-one"/><div className="closing-orbit orbit-two"/><div className="closing-content"><p className="section-eyebrow">FOR COOPERATIVES · NGOS · INPUT NETWORKS</p><h2>Make every next step<br/>easier to <em>reach.</em></h2><p>Give your field teams one connected view of the support farmers need and the options available nearby.</p><a className="button button-cream" href={`${dashboardUrl}/login`}>Enter partner workspace <span>↗</span></a></div><div className="closing-stamp"><BrandMark/><span>GROW<br/>TOGETHER</span></div></section>

      <footer className="site-footer"><div className="footer-top"><a className="wordmark" href="#home"><BrandMark/><span>harvest<span className="wordmark-os">os</span></span></a><span className="footer-motto">Better connections. Stronger harvests.</span><a className="footer-up" href="#home">BACK TO TOP ↑</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} HARVESTOS · BUILT FOR FARMER NETWORKS</span><div><a href="#system">System design</a><a href={`${dashboardUrl}/login`}>Partner sign in</a><a href="https://github.com/opeblow/HarvestOS" target="_blank" rel="noreferrer">GitHub ↗</a></div></div></footer>
    </main>
  );
}

function BrandMark(){return <span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 40 40"><path d="M20 31V17m0 8c-6 0-10-4-11-10 6 0 10 4 11 10Zm0-5c0-7 4-12 11-13 0 7-4 12-11 13Z"/><path d="M13 32h14"/></svg></span>}

function ProductPreview(){return <div className="preview-wrap"><div className="preview-backdrop"><div className="backdrop-sun"/><div className="backdrop-stem stem-a"/><div className="backdrop-stem stem-b"/><div className="backdrop-stem stem-c"/><span className="backdrop-label">ONE FARMER. ONE CONNECTED JOURNEY.</span></div><div className="preview-window"><div className="preview-top"><span className="window-lights"><i/><i/><i/></span><span>HARVESTOS <i>/</i> FIELD OPERATIONS</span><span className="preview-live"><i/> PREVIEW</span></div><div className="preview-body"><div className="preview-sidebar"><BrandMark/><span className="side-active">◫</span><span>☷</span><span>⌖</span><span>↗</span><div className="side-avatar">KO</div></div><div className="preview-main"><div className="preview-heading"><span>FARMER NETWORK <i>·</i> TODAY</span><b>Conversation overview <span>↗</span></b></div><div className="preview-stat-row"><div><small>ACTIVE JOURNEYS</small><b>In progress</b><span className="stat-rule"/></div><div><small>CHANNELS</small><b>SMS <i>·</i> WhatsApp</b><span>Context carries through</span></div><div><small>PARTNER VIEW</small><b>Connected</b><span>Shared session state</span></div></div><div className="preview-activity"><div className="activity-head"><span>RECENT FIELD ACTIVITY</span><span>PRODUCT PREVIEW</span></div><div className="activity-row"><span className="activity-avatar avatar-sage">AB</span><span className="activity-details"><b>Crop support request</b><small>Maize · symptom reported</small></span><span className="activity-channel">SMS</span><span className="activity-stage">Listening <i/></span></div><div className="activity-row"><span className="activity-avatar avatar-ochre">YK</span><span className="activity-details"><b>Photo follow-up</b><small>Crop evidence · attached</small></span><span className="activity-channel wa">WA</span><span className="activity-stage stage-review">Review <i/></span></div><div className="activity-row"><span className="activity-avatar avatar-blue">FM</span><span className="activity-details"><b>Input options shared</b><small>Dealer match · local supply</small></span><span className="activity-channel rcs">RCS</span><span className="activity-stage stage-connected">Connected <i/></span></div><div className="preview-bottom"><span><i/> SAMPLE INTERFACE · NOT LIVE CUSTOMER DATA</span><span>SESSION CONTINUITY <b>↗</b></span></div></div></div></div></div><div className="preview-caption"><span>01 / PARTNER OPERATIONS</span><span>SEE THE WHOLE STORY, NOT JUST THE MESSAGE.</span></div></div>}
